version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies ...
      - cd backend && npm install
  build:
    commands:
      - echo Build Completed Successfully 🎉

artifacts:
  files:
    - '**/*'
